apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-esp-redis
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: esp-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: esp-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: esp-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        timestamp: {{ .Release.Time }}
    spec:
      containers:
      - name: redis
        image: redis:5.0.3-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp-redis
          containerPort: 6379
      restartPolicy: Always
