apiVersion: verify.gov.uk/v1beta1
kind: Metadata
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ .Release.Name }}-proxy-node-metadata
  namespace: {{ .Release.Namespace }}
spec:
  id: _entities
  type: proxy
  data:
    entityID: {{ include "gateway.entityID" . }}
    postURL: https://{{ include "gateway.host" . }}/SAML2/SSO/POST
    redirectURL: https://{{ include "gateway.host" . }}/Redirect
    orgName: Government Digital Service
    orgDisplayName: GDS
    orgURL: https://www.gov.uk/verify
    contactCompany: GDS
    contactGivenName: GOV.UK Verify
    contactSurname: Support
    contactEmail: idasupport@digital.cabinet-office.gov.uk
  enabled: true
  samlSigningCertRequest:
    countryCode: GB
    commonName: Verify Proxy Node SAML Signing
    expiryMonths: 3
    organization: Cabinet Office
    organizationUnit: GDS
    location: London
  certificateAuthority:
    secretName: {{ .Release.Name }}-proxy-node-metadata-signing-cert
    namespace: {{ .Release.Namespace }}
