{{- if .Values.stubConnector.enabled -}}
apiVersion: verify.gov.uk/v1beta1
kind: Metadata
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ .Release.Name }}-connector-metadata
  namespace: {{ .Release.Namespace }}
spec:
  id: _entities
  type: connector
  data:
    entityID: {{ include "connector.entityID" . }}
    postURL: https://{{ include "stubConnector.host" . }}/SAML2/Response/POST
    redirectURL: https://{{ include "stubConnector.host" . }}/Redirect
    orgName: {{ .Release.Name }}
    orgDisplayName: {{ .Release.Name }}
    orgURL: https://{{ include "stubConnector.host" . }}
    contactCompany: Stub Connector
    contactGivenName: Jeff
    contactSurname: Jefferson
    contactEmail: jeff@example.local
  enabled: true
  samlSigningCertRequest:
    countryCode: EU
    commonName: Stub Connector SAML Signing
    expiryMonths: 3
    organization: EU Member State
    organizationUnit: Test
    location: European Union
  certificateAuthority:
    secretName: {{ .Release.Name }}-connector-metadata-signing-cert
    namespace: {{ .Release.Namespace }}
{{- end -}}
