{{- if .Values.stubConnector.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-connector-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-connector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  hosts:
  - {{ include "stubConnector.host" . }}
  gateways:
  - {{ .Release.Name }}-connector-ingress
  http:
    - route:
      - destination:
          host: {{ .Release.Name }}-connector
          port:
            number: 80
  exportTo:
  - "."
{{- end -}}
