---
apiVersion: concourse.govsvc.uk/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: killswitch
spec:
  exposed: false
  paused: true
  config:

    task_toolbox: &task_toolbox
      type: docker-image
      source:
        repository: ((concourse.task-toolbox-image))
        tag: ((concourse.task-toolbox-tag))

    slack_defaults: &slack_defaults
      channel: "#verify-2ndline"
      silent: true
      icon_emoji: ':lock:'

    run: &create-lock-file
      path: ruby
      args:
        - -e
        - |
          require 'json'

          content = {
            is_locked: ENV['IS_LOCKED'] == 'true'
          }

          puts "Lock file content is now: #{content.to_json}"

          File.write("lock-dir/#{Time.now.to_i}.lock", content.to_json)

    resource_types:
      - name: slack-notification
        type: docker-image
        source:
          repository: cfcommunity/slack-notification-resource

    resources:

      - name: verify-slack
        type: slack-notification
        source:
          url: ((verify-2nd-line-slack-webhook.url))

      - name: production-lock
        type: s3
        source:
          bucket: ((production-lock.S3BucketName))
          region_name: ((production-lock.S3BucketRegion))
          access_key_id: ((pipeline.AccessKeyID))
          secret_access_key: ((pipeline.SecretAccessKey))
          session_token: ((pipeline.SessionToken))
          regexp: lock/(.*).lock
          initial_path: 0.lock
          initial_content_text: |
            {
              "is_locked": false
            }

    jobs:

    - name: lock-prod-deploy
      serial: true
      plan:
        - do: &lock-proxy-node-pipeline
          - task: create-lockfile
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: govsvc/aws-ruby
                  tag: 2.6.1
              outputs:
                - name: lock-dir
              params:
                IS_LOCKED: 'true'
              run: *create-lock-file
          - put: production-lock
            params:
              file: lock-dir/*.lock
        - put: verify-slack
          params:
            << : *slack_defaults
            text: "The Proxy-Node Production deploy pipeline has been locked"

    - name: unlock-prod-deploy
      serial: true
      plan:
        - do:
            - task: create-lockfile
              config:
                platform: linux
                image_resource:
                  type: docker-image
                  source:
                    repository: govsvc/aws-ruby
                    tag: 2.6.1
                outputs:
                  - name: lock-dir
                params:
                  IS_LOCKED: 'false'
                run: *create-lock-file
            - put: production-lock
              params:
                file: lock-dir/*.lock
        - put: verify-slack
          params:
            << : *slack_defaults
            text: "The Proxy-Node Production deploy pipeline has been unlocked"
            icon_emoji: ':unlock:'

    - name: kill-and-lock-prod
      plan:
        - task: delete-resources
          timeout: 10m
          config:
            platform: linux
            image_resource: *task_toolbox
            params:
              KUBERNETES_SERVICE_ACCOUNT: ((namespace-deployer))
              KUBERNETES_TOKEN: ((namespace-deployer.token))
              NAMESPACE: ((namespace-deployer.namespace))
            run:
              path: /bin/bash
              args:
                - -euc
                - |
                  echo "configuring kubectl"
                  echo "${KUBERNETES_SERVICE_ACCOUNT}" | jq -r .["ca.crt"] > ca.crt
                  kubectl config set-cluster self --server=https://kubernetes.default --certificate-authority=ca.crt
                  kubectl config set-credentials deployer --token "${KUBERNETES_TOKEN}"
                  kubectl config set-context deployer --user deployer --cluster self
                  kubectl config use-context deployer

                  kubectl -n "${NAMESPACE}" delete virtualservices,deployments -l app.kubernetes.io/instance=production
        - do: *lock-proxy-node-pipeline
        - put: verify-slack
          params:
            << : *slack_defaults
            text: "The Proxy-Node Production :skull: killswitch :skull: has been pulled, which means the Production instance has been deleted and the Production deploy pipeline has been locked. See $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME"